language: ruby
cache:
  bundler: true
rvm:
  - 1.9.3
  - 2.1.2
  - 2.3.1
services:
  - mongodb
  - postgresql
before_script:
    - psql -c 'create database mosql;' -U postgres
env:
  - MONGOSQL_TEST_SQL=postgres://localhost/mosql
