language: ruby
cache:
  bundler: true
rvm:
  - 2.3.3
  - 2.4.1
services:
  - mongodb
  - postgresql
before_script:
    - psql -c 'create database mosql;' -U postgres
env:
  - MONGOSQL_TEST_SQL=postgres://localhost/mosql
